### PR TITLE
fix in preparation for JuliaLang/julia#37573

### PR DESCRIPTION
**Pull request by simeonschaub**
Test case is actually from JuliaPlanners/PDDL.jl.

### CODE REVIEW

**Comment by ztangent** [comment]
Thanks for the catch! It looks like this is failing on older versions of Julia -- could you write it so that the parser is conditional on the Julia version?

**Comment by simeonschaub** [comment]
Yes, I am currently looking into it. It's just weird, because this shouldn't actually error.

**Comment by simeonschaub** [comment]
Actually, `@varsub` is already a bit broken:
```julia
julia> @varsub {X => (a,)}
ERROR: LoadError: syntax: invalid syntax (escape (call (core tuple) (outerref a)))
Stacktrace:
 [1] top-level scope at none:1
 [2] eval at ./boot.jl:331 [inlined]
 [3] eval at /home/simeon/.julia/dev/Julog/src/Julog.jl:1 [inlined]
 [4] (::Julog.var"#8#11")(::Expr) at ./none:0
 [5] iterate at ./generator.jl:47 [inlined]
 [6] collect(::Base.Generator{Array{Any,1},Julog.var"#8#11"}) at ./array.jl:686
 [7] @varsub(::LineNumberNode, ::Module, ::Any) at /home/simeon/.julia/dev/Julog/src/parse.jl:138
in expression starting at REPL[15]:1
```

**Comment by simeonschaub** [comment]
Ok, both should be fixed now.

**Comment by ztangent** [comment]
Thanks! Unfortunately it looks like this still causes issues if you try to do interpolation with a `@varsub`:

```julia
julia> x = 1; y = @julog y
julia> @varsub {A => $x}
ERROR: LoadError: UndefVarError: x not defined
julia> @varsub {A => :y}
ERROR: LoadError: UndefVarError: y not defined
```

**Comment by simeonschaub** [comment]
Note that this was not caused by this PR. I have a fix for this particular issue, but using `eval` inside a macro like this is generally not a good idea and will also prevent it from working correctly in local scope. I would recommend refactoring this to splice the output of `parse_term` directly into the AST returned by the macro instead, which should be a much less fragile solution.

**Comment by ztangent** [comment]
Ah right, good point re returning an expression -- I think I wrote all this code when I was relatively new to Julia. I'll merge this for now, then make the fix in a separate branch. Thanks!

**Pull request merged**
